# weird since github doesn't detect this workflow from previous update, is there something wrong? 

name: Go

on:
  push:
    branches: [ "feat/cicd" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb
        env:
          MARIADB_USER: santo
          MARIADB_PASSWORD: sembodo
          MARIADB_ROOT_PASSWORD: sujiwo-tejo
          MARIADB_DATABASE: blog-be-using-go
        ports:
          - 3306:3306
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build and run
      run: |
        cd cmd/customer
        go build -v .
        chmod 775 customer
        ./customer

    - name: Test
      run: |
        cd cmd/customer
        cp config.yml.e2e-test.example config.yaml
        go install github.com/karincake/emping
        cd ../../test/e2e
        emping customer-test.yml
        
